stages:
  - lint
  - validate
  - test

default:
  interruptible: true

.default-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.pr-only-rule:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

yaml-lint:
  stage: lint
  extends: .default-rules
  image: ghcr.io/google/yamlfmt:0.21.0@sha256:015f4f1e818b38cb72bec2d4baa5d312d3a5f40c6c22ff3fef35a5415095b7f2
  script:
    - yamlfmt -lint .

docker-compose-config:
  stage: validate
  extends: .default-rules
  image: docker.io/library/docker:29.8.0-cli@sha256:eccaacfeed644c7de222ff047483568cb988dde95476fbaaf10ea2d04921bb66
  services:
    - name: docker.io/library/docker:29.8.0-dind@sha256:5efed980cba3fc126cf54e21a5a6ff8849d05b6e0623d6e7612f48e9cd6cd17e
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker compose -f compose.yml config

podman-compose-config:
  stage: validate
  extends: .default-rules
  image: quay.io/podman/stable:v5.8.4@sha256:c03377868e6cae145b93c3ecca0c1a68e827f6bba8c1e8259345676cf5c1a51f

  before_script:
    - microdnf install -y python3-pip git || dnf install -y python3-pip git
    - pip3 install podman-compose

  script:
    - podman-compose -f compose.yml config

docker-compose-pull-amd64:
  stage: test
  extends: .pr-only-rule
  image: docker.io/library/docker:29.8.0-cli@sha256:eccaacfeed644c7de222ff047483568cb988dde95476fbaaf10ea2d04921bb66
  services:
    - name: docker.io/library/docker:29.8.0-dind@sha256:5efed980cba3fc126cf54e21a5a6ff8849d05b6e0623d6e7612f48e9cd6cd17e
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker compose pull
  tags:
    - saas-linux-small-amd64

docker-compose-pull-arm64:
  stage: test
  extends: .pr-only-rule
  image: docker.io/library/docker:29.8.0-cli@sha256:eccaacfeed644c7de222ff047483568cb988dde95476fbaaf10ea2d04921bb66
  services:
    - name: docker.io/library/docker:29.8.0-dind@sha256:5efed980cba3fc126cf54e21a5a6ff8849d05b6e0623d6e7612f48e9cd6cd17e
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker compose pull
  tags:
    - saas-linux-small-arm64

podman-compose-pull-amd64:
  stage: test
  extends: .pr-only-rule
  image: quay.io/podman/stable:v5.8.4@sha256:c03377868e6cae145b93c3ecca0c1a68e827f6bba8c1e8259345676cf5c1a51f

  before_script:
    - microdnf install -y python3-pip git || dnf install -y python3-pip git
    - pip3 install podman-compose

  script:
    - podman-compose pull
  tags:
    - saas-linux-small-amd64

podman-compose-pull-arm64:
  stage: test
  extends: .pr-only-rule
  image: quay.io/podman/stable:v5.8.4@sha256:c03377868e6cae145b93c3ecca0c1a68e827f6bba8c1e8259345676cf5c1a51f

  before_script:
    - microdnf install -y python3-pip git || dnf install -y python3-pip git
    - pip3 install podman-compose

  script:
    - podman-compose pull
  tags:
    - saas-linux-small-arm64