stages:
  - lint
  - validate
  - test

default:
  interruptible: true

.default-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.pr-only-rule:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

yaml-lint:
  stage: lint
  extends: .default-rules
  image: ghcr.io/google/yamlfmt:0.21.0@sha256:015f4f1e818b38cb72bec2d4baa5d312d3a5f40c6c22ff3fef35a5415095b7f2
  script:
    - yamlfmt -lint .

docker-compose-config:
  stage: validate
  extends: .default-rules
  image: docker.io/library/docker:29.5.3-cli@sha256:11e1133c30f3ceb73c6bdc7dfb78b3f9ed8e8e0d1d0400e91c5ec2eb240bf2ff
  services:
    - name: docker.io/library/docker:29.5.3-dind@sha256:7d85d0eda291f1a7ab6df4a9d1802b5ad4cf9145a088bd11188c78dcb5c7392b
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker compose -f compose.yml config

podman-compose-config:
  stage: validate
  extends: .default-rules
  image: quay.io/podman/stable:v5.8.2@sha256:663e0dbf407987b7db3f20d3588c283a8228db17b282d2029a482d4d47e36964

  before_script:
    - microdnf install -y python3-pip git || dnf install -y python3-pip git
    - pip3 install podman-compose

  script:
    - podman-compose -f compose.yml config

docker-compose-pull-amd64:
  stage: test
  extends: .pr-only-rule
  image: docker.io/library/docker:29.5.3-cli@sha256:11e1133c30f3ceb73c6bdc7dfb78b3f9ed8e8e0d1d0400e91c5ec2eb240bf2ff
  services:
    - name: docker.io/library/docker:29.5.3-dind@sha256:7d85d0eda291f1a7ab6df4a9d1802b5ad4cf9145a088bd11188c78dcb5c7392b
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker compose pull
  tags:
    - saas-linux-small-amd64

docker-compose-pull-arm64:
  stage: test
  extends: .pr-only-rule
  image: docker.io/library/docker:29.5.3-cli@sha256:11e1133c30f3ceb73c6bdc7dfb78b3f9ed8e8e0d1d0400e91c5ec2eb240bf2ff
  services:
    - name: docker.io/library/docker:29.5.3-dind@sha256:7d85d0eda291f1a7ab6df4a9d1802b5ad4cf9145a088bd11188c78dcb5c7392b
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker compose pull
  tags:
    - saas-linux-small-arm64

podman-compose-pull-amd64:
  stage: test
  extends: .pr-only-rule
  image: quay.io/podman/stable:v5.8.2@sha256:663e0dbf407987b7db3f20d3588c283a8228db17b282d2029a482d4d47e36964

  before_script:
    - microdnf install -y python3-pip git || dnf install -y python3-pip git
    - pip3 install podman-compose

  script:
    - podman-compose pull
  tags:
    - saas-linux-small-amd64

podman-compose-pull-arm64:
  stage: test
  extends: .pr-only-rule
  image: quay.io/podman/stable:v5.8.2@sha256:663e0dbf407987b7db3f20d3588c283a8228db17b282d2029a482d4d47e36964

  before_script:
    - microdnf install -y python3-pip git || dnf install -y python3-pip git
    - pip3 install podman-compose

  script:
    - podman-compose pull
  tags:
    - saas-linux-small-arm64